spring:
  application:
    name: aronim-cloud-gateway
  thymeleaf:
    cache: false

server:
  port: 8000

zuul:
  routes:

    # Component Application
    component-resources:
      path: /resources/component/**
      serviceId: aronim-cloud-component
      stripPrefix: false
    component-api:
      path: /api/components/**
      serviceId: aronim-cloud-component
      stripPrefix: false

    # User Application
    user-api:
      path: /api/users/**
      serviceId: aronim-cloud-user
      stripPrefix: false
    user-resources:
      path: /resources/user/**
      serviceId: aronim-cloud-user
      stripPrefix: false

    # Organisation Application
    organisation-api:
      path: /api/organisations/**
      serviceId: aronim-cloud-organisation
      stripPrefix: false
    organisation-resources:
      path: /resources/organisation/**
      serviceId: aronim-cloud-organisation
      stripPrefix: false

    # Menu Application
    menu-api:
      path: /api/menus/**
      serviceId: aronim-cloud-menu
      stripPrefix: false
    menu-resources:
      path: /resources/menu/**
      serviceId: aronim-cloud-menu
      stripPrefix: false

    # Incubator Application
#    organisation-api:
#      path: /api/organisations/**
#      serviceId: aronim-cloud-organisation
#      stripPrefix: false
#    organisation-resources:
#      path: /resources/organisation/**
#      serviceId: aronim-cloud-organisation
#      stripPrefix: false
