spring:
  application:
    name: kdc-gateway

server:
  port: 8000

zuul:
  routes:

    # Component Component
    component-resources:
      path: /resources/component/**
      serviceId: kdc-component
      stripPrefix: false
    component-api:
      path: /api/components/**
      serviceId: kdc-component
      stripPrefix: false

    # User Component
    user-api:
      path: /api/users/**
      serviceId: kdc-user
      stripPrefix: false
    user-resources:
      path: /resources/user/**
      serviceId: kdc-user
      stripPrefix: false
